{% set name = "keras-tuner" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa4446b5732db696c518f19e0efccf89a49dcc3ed2034c423d3addc25e9b172c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - Ipython
    - kt-legacy
    - numpy
    - packaging
    - requests
    - scikit-learn
    - scipy
    - tensorboard
    - keras-core
    - protobuf


test:
  imports:
    - keras_tuner
    - keras_tuner.applications
    - keras_tuner.engine
    - keras_tuner.oracles
    - keras_tuner.tuners
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/keras-team/keras-tuner
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Hypertuner for Keras
  doc_url: https://keras-team.github.io/keras-tuner/
  dev_url: https://github.com/keras-team/keras-tuner

extra:
  recipe-maintainers:
    - anselmoo
    - oblute
    - rluria14
    - Tata17
    - mxr-conda
