{% set name = "keras-tuner" %}
{% set version = "1.4.7" %}

package:
  name: keras-tuner-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6befd25ee81476e6207d8ca7ed7dc674b8194437cfa0b127294cd00da905ff22

build:
  noarch: python
  number: 1

outputs:
  - name: {{ name }}
    build:
      script: {{ PYTHON }} -m pip install . -vv
    requirements:
      host:
        - pip
        - python >=3.8
      run:
        - python >=3.8
        - keras
        - packaging
        - requests    
        - kt-legacy
    test:
      imports:
        - keras_tuner
        - keras_tuner.applications
        - keras_tuner.engine
        - keras_tuner.oracles
        - keras_tuner.tuners
      commands:
        - pip check
      requires:
        - pip

  - name: {{ name }}-bayesian
    requirements:
      host:
        - python >=3.8
      run:
        - python >=3.8
        - {{ pin_subpackage('keras-tuner', exact=True) }}
        - scikit-learn
        - scipy
    test:
      imports:
        - keras_tuner.tuners.bayesian

about:
  home: https://github.com/keras-team/keras-tuner
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Hypertuner for Keras
  doc_url: https://keras-team.github.io/keras-tuner/
  dev_url: https://github.com/keras-team/keras-tuner

extra:
  recipe-maintainers:
    - anselmoo
    - oblute
    - rluria14
    - Tata17
    - mxr-conda
    - DManowitz
  feedstock-name: keras-tuner
